const aosAnimations = [
    'fade',
    'fade-up',
    'fade-down',
    'fade-left',
    'fade-right',
    'slide-up',
    'slide-down',
    'slide-left',
    'slide-right',
    'zoom-in',
    'zoom-in-up',
    'zoom-in-down',
    'zoom-in-left',
    'zoom-in-right',
    'zoom-out',
    'zoom-out-up',
    'zoom-out-down',
    'zoom-out-left',
    'zoom-out-right',
    'flip-left',
    'flip-right',
    'flip-up',
    'flip-down',
    'fade-up-right',
    'fade-up-left',
    'fade-down-right',
    'fade-down-left',
    'zoom-in-fade',
    'zoom-out-fade',
    'fade-zoom-in'
  ];


export  default aosAnimations;
